apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: user12hellogos.hellogo.example.com
spec:
  group: hellogo.example.com
  names:
    kind: User12hellogo
    listKind: User12hellogoList
    plural: user12hellogos
    singular: user12hellogo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
